### ISSUE TITLE
Log model responses directly to file and reuse them for debugging

### ISSUE THREAD

**Issue by bauersimon** [symflower/eval-dev-quality#181] opened 2024-06-12 07:54 UTC
Goal, be able to use exactly 1:1 responses from a previous run to debug the evaluation logic.

- [ ] log model responses directly to files (either on provider query response level or generate test level)
- [ ] add dummy model that takes these files and responds accordingly (essentially mimicking/replaying the original model responses)

**Comment by ahumenberger** [comment] 2024-07-04 08:02
Duplicate of #204. Closing.

**Closed by ahumenberger** 2024-07-04 08:02 UTC
Labels: duplicate, enhancement
